version: '3.8'

services:
  backend:
    container_name: auto-x-ui-container
    image: auto-x-ui:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: prod
    restart: unless-stopped
    stdin_open: true
    network_mode: host
    ports:
      - "8910:8910"
    command: [ "serve", "-s", "dist", "-l", "8910" ]
networks:
  bridge_network:
    driver: host
